### ISSUE TITLE
Bug: the bottom of game will be jacked up

### ISSUE THREAD

**Issue by ForkKILLET** [candybox2/candybox#5]
I played your game in Chrome. The download bar and dev tool make the bottom bar of the game change its position.  
Perhaps we can make the bottom bar `position: static;` or `background-color: white;`,  
so that it won't overlap with the game part.

    by a Chinese player ForkKILET.

**Comment by liamhmn** [comment]
#3 hi

- [ ]

**Comment by kvaps** [comment]
probably fixed
