### ISSUE TITLE
Removal of name

### ISSUE THREAD

**Issue by xZakko** [candybox2/candybox#8]
I'm the old translator for the Danish FAQ 2, ( candybox/da/faq2.html ) and for personal reasons I want to keep my name and aliases off the internet (as much as possible anyway.) 

On line 57 of the mentioned FAQ 2, it says who it's translated by - all I request is that line is removed or the names, aliases and the link is censored.

Apologies if this is the wrong way to go about things, I am not very experienced with GitHub.

**Comment by kvaps** [comment]
Hi @xZakko, we can remove your name from the current version of candybox, but it never will be deleted from the git history and the other forks.

Also it always be persist in the original version which is currently unmaintained and placed on https://web.archive.org.

If this satisfy your needs, please feel free to edit the source page as you want:
https://github.com/candybox2/candybox/blob/master/da/faq2.html

And make pull request for this change, I'm going to accept it!

Regards!

**Comment by xZakko** [comment]
The issue is mainly the google search result coming from "https://candybox2.github.io/candybox/da/faq2.html". I'm afraid I am unfamiliar with GitHub and haven't tried making a pull request. Apologies for the inconvencience, if I did it incorrectly.

Thank you for the help.

**Comment by kvaps** [comment]
You done this right.
Merged, thank you for your contribution!
